---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
theme: dark
jwt_secret: Secretjwt
default_redirection_url: Dominio
totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: public.example.com
      policy: bypass
    # one_factor
    - domain: public.example.com
      policy: one_factor
    #two_factor
    - domain: public.example.com
      policy: two_factor

session:
  name: authelia_session
  secret: Secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: Dominio 

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: Secret
  local:
    path: /config/db.sqlite3

notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /config/notification.txt
...