version: '3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /path/authelia/config:/config
    networks:
      - lan
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`dominio`)'
      - 'traefik.http.services.authelia.loadbalancer.server.port=9091'
      - 'traefik.http.routers.authelia.entrypoints=web, websecure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://dominio'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    healthcheck:
      disable: true
networks:
  lan:
    external: true