---
###############################################################
#                         Users Database                      #
###############################################################

users:
  authelia:
    displayname: "authelia"
    password: 
    email: authelia
    groups:
      - admins
      - dev

...