version: "3"
services:
  portainer:
    container_name: portainer
    iamge: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/Docker.sock
      - portainer_data:/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host('portainer.dominio')"
      - "traefik.http.routers.api.entrypoints=web, websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - lan

networks:
  lan:
    external: true

volumes:
  portainer_data:
    external: true