version: "3"
services:
  portainer:
    container_name: portainer
    iamge: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    ports:
      - 9000:9000

volumes:
  portainer_data:
    external: true