global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

tls:
  certificates:
    - certFile: "path/cert.crt"
    - keyFile: "path/key.key"
    stores:
      -default
  stores:
    default:
      defaultCertificate:
        certFile: "path/key.key"
        keyFile: "path/key.key"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true