version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /path/heidmallConfig:/config
    restart: unless-stopped
    networks: 
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`dominio`)"
      - "traefik.http.routers.heimdall.entrypoints=web, websecure"
      - "traefik.http.routers.heimdall.tls=true"
      
networks: 
  lan:
    external: true